{% set name = "sagemaker-tensorflow-serving-container" %}
{% set version = "1.6.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6966776de8ba7e49cd4af0b5c269adb3bce7d9a5b961e735f75c08d7bc5f499b

build:
  number: 0
  script:
    - cp -r $SRC_DIR $SP_DIR/sagemaker_tensorflow_serving_container
  skip: True  # [win or py2k]

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - sagemaker_tensorflow_serving_container

about:
  home: https://github.com/aws/sagemaker-tensorflow-serving-container
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'SageMaker TensorFlow Serving Container is an a open source project that builds docker images for running TensorFlow Serving on Amazon SageMaker.'
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_tf.html
  dev_url: https://github.com/aws/sagemaker-tensorflow-serving-container

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
